package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String busId;
	private ModeloBus modeloBus;
	private String placa;
	private Integer numero;
	private Date fechaIngreso;
	private Integer capacidadTotal;
	private String caracteristicas;
	private Set propietarioBuses = new HashSet(0);
	private Set tarjetas = new HashSet(0);
	private Set detalleGrupos = new HashSet(0);

	public Bus() {
	}

	public Bus(String busId, ModeloBus modeloBus, String placa, Date fechaIngreso) {
		this.busId = busId;
		this.modeloBus = modeloBus;
		this.placa = placa;
		this.fechaIngreso = fechaIngreso;
	}

	public Bus(String busId, ModeloBus modeloBus, String placa, Integer numero, Date fechaIngreso,
			Integer capacidadTotal, String caracteristicas, Set propietarioBuses, Set tarjetas, Set detalleGrupos) {
		this.busId = busId;
		this.modeloBus = modeloBus;
		this.placa = placa;
		this.numero = numero;
		this.fechaIngreso = fechaIngreso;
		this.capacidadTotal = capacidadTotal;
		this.caracteristicas = caracteristicas;
		this.propietarioBuses = propietarioBuses;
		this.tarjetas = tarjetas;
		this.detalleGrupos = detalleGrupos;
	}

	public String getBusId() {
		return this.busId;
	}

	public void setBusId(String busId) {
		this.busId = busId;
	}

	public ModeloBus getModeloBus() {
		return this.modeloBus;
	}

	public void setModeloBus(ModeloBus modeloBus) {
		this.modeloBus = modeloBus;
	}

	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Integer getCapacidadTotal() {
		return this.capacidadTotal;
	}

	public void setCapacidadTotal(Integer capacidadTotal) {
		this.capacidadTotal = capacidadTotal;
	}

	public String getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(String caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	public Set getPropietarioBuses() {
		return this.propietarioBuses;
	}

	public void setPropietarioBuses(Set propietarioBuses) {
		this.propietarioBuses = propietarioBuses;
	}

	public Set getTarjetas() {
		return this.tarjetas;
	}

	public void setTarjetas(Set tarjetas) {
		this.tarjetas = tarjetas;
	}

	public Set getDetalleGrupos() {
		return this.detalleGrupos;
	}

	public void setDetalleGrupos(Set detalleGrupos) {
		this.detalleGrupos = detalleGrupos;
	}

}
