package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaIncidencia generated by hbm2java
 */
public class CategoriaIncidencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String categoriaIncidenciaId;
	private String categoria;
	private Set incidencias = new HashSet(0);

	public CategoriaIncidencia() {
	}

	public CategoriaIncidencia(String categoriaIncidenciaId, String categoria) {
		this.categoriaIncidenciaId = categoriaIncidenciaId;
		this.categoria = categoria;
	}

	public CategoriaIncidencia(String categoriaIncidenciaId, String categoria, Set incidencias) {
		this.categoriaIncidenciaId = categoriaIncidenciaId;
		this.categoria = categoria;
		this.incidencias = incidencias;
	}

	public String getCategoriaIncidenciaId() {
		return this.categoriaIncidenciaId;
	}

	public void setCategoriaIncidenciaId(String categoriaIncidenciaId) {
		this.categoriaIncidenciaId = categoriaIncidenciaId;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Set getIncidencias() {
		return this.incidencias;
	}

	public void setIncidencias(Set incidencias) {
		this.incidencias = incidencias;
	}

}
