package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Cronograma generated by hbm2java
 */
public class Cronograma implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String cronogramaId;
	private Periodo periodo;
	private Set detalleCronogramas = new HashSet(0);

	public Cronograma() {
	}

	public Cronograma(String cronogramaId, Periodo periodo) {
		this.cronogramaId = cronogramaId;
		this.periodo = periodo;
	}

	public Cronograma(String cronogramaId, Periodo periodo, Set detalleCronogramas) {
		this.cronogramaId = cronogramaId;
		this.periodo = periodo;
		this.detalleCronogramas = detalleCronogramas;
	}

	public String getCronogramaId() {
		return this.cronogramaId;
	}

	public void setCronogramaId(String cronogramaId) {
		this.cronogramaId = cronogramaId;
	}

	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	public Set getDetalleCronogramas() {
		return this.detalleCronogramas;
	}

	public void setDetalleCronogramas(Set detalleCronogramas) {
		this.detalleCronogramas = detalleCronogramas;
	}

}
