package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * DetalleCronograma generated by hbm2java
 */
public class DetalleCronograma implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String detalleCronogramaId;
	private Cronograma cronograma;
	private Ruta ruta;
	private Set salidaBuses = new HashSet(0);

	public DetalleCronograma() {
	}

	public DetalleCronograma(String detalleCronogramaId, Cronograma cronograma, Ruta ruta) {
		this.detalleCronogramaId = detalleCronogramaId;
		this.cronograma = cronograma;
		this.ruta = ruta;
	}

	public DetalleCronograma(String detalleCronogramaId, Cronograma cronograma, Ruta ruta, Set salidaBuses) {
		this.detalleCronogramaId = detalleCronogramaId;
		this.cronograma = cronograma;
		this.ruta = ruta;
		this.salidaBuses = salidaBuses;
	}

	public String getDetalleCronogramaId() {
		return this.detalleCronogramaId;
	}

	public void setDetalleCronogramaId(String detalleCronogramaId) {
		this.detalleCronogramaId = detalleCronogramaId;
	}

	public Cronograma getCronograma() {
		return this.cronograma;
	}

	public void setCronograma(Cronograma cronograma) {
		this.cronograma = cronograma;
	}

	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	public Set getSalidaBuses() {
		return this.salidaBuses;
	}

	public void setSalidaBuses(Set salidaBuses) {
		this.salidaBuses = salidaBuses;
	}

}
