package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * DetalleGrupo generated by hbm2java
 */
public class DetalleGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String detalleGrupoId;
	private Bus bus;
	private Grupo grupo;
	private Set salidaBuses = new HashSet(0);

	public DetalleGrupo() {
	}

	public DetalleGrupo(String detalleGrupoId, Bus bus, Grupo grupo) {
		this.detalleGrupoId = detalleGrupoId;
		this.bus = bus;
		this.grupo = grupo;
	}

	public DetalleGrupo(String detalleGrupoId, Bus bus, Grupo grupo, Set salidaBuses) {
		this.detalleGrupoId = detalleGrupoId;
		this.bus = bus;
		this.grupo = grupo;
		this.salidaBuses = salidaBuses;
	}

	public String getDetalleGrupoId() {
		return this.detalleGrupoId;
	}

	public void setDetalleGrupoId(String detalleGrupoId) {
		this.detalleGrupoId = detalleGrupoId;
	}

	public Bus getBus() {
		return this.bus;
	}

	public void setBus(Bus bus) {
		this.bus = bus;
	}

	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Set getSalidaBuses() {
		return this.salidaBuses;
	}

	public void setSalidaBuses(Set salidaBuses) {
		this.salidaBuses = salidaBuses;
	}

}
