package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String grupoId;
	private String grupo;
	private Set detalleGrupos = new HashSet(0);

	public Grupo() {
	}

	public Grupo(String grupoId) {
		this.grupoId = grupoId;
	}

	public Grupo(String grupoId, String grupo, Set detalleGrupos) {
		this.grupoId = grupoId;
		this.grupo = grupo;
		this.detalleGrupos = detalleGrupos;
	}

	public String getGrupoId() {
		return this.grupoId;
	}

	public void setGrupoId(String grupoId) {
		this.grupoId = grupoId;
	}

	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	public Set getDetalleGrupos() {
		return this.detalleGrupos;
	}

	public void setDetalleGrupos(Set detalleGrupos) {
		this.detalleGrupos = detalleGrupos;
	}

}
