package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Locacion generated by hbm2java
 */
public class Locacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String locacionId;
	private String distrito;
	private String sector;
	private Set empleados = new HashSet(0);
	private Set socios = new HashSet(0);
	private Set puntos = new HashSet(0);

	public Locacion() {
	}

	public Locacion(String locacionId, String distrito) {
		this.locacionId = locacionId;
		this.distrito = distrito;
	}

	public Locacion(String locacionId, String distrito, String sector, Set empleados, Set socios, Set puntos) {
		this.locacionId = locacionId;
		this.distrito = distrito;
		this.sector = sector;
		this.empleados = empleados;
		this.socios = socios;
		this.puntos = puntos;
	}

	public String getLocacionId() {
		return this.locacionId;
	}

	public void setLocacionId(String locacionId) {
		this.locacionId = locacionId;
	}

	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

	public Set getSocios() {
		return this.socios;
	}

	public void setSocios(Set socios) {
		this.socios = socios;
	}

	public Set getPuntos() {
		return this.puntos;
	}

	public void setPuntos(Set puntos) {
		this.puntos = puntos;
	}

}
