package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * ModeloBus generated by hbm2java
 */
public class ModeloBus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String modeloBusId;
	private String modelo;
	private String caracteristicas;
	private Set buses = new HashSet(0);

	public ModeloBus() {
	}

	public ModeloBus(String modeloBusId, String modelo) {
		this.modeloBusId = modeloBusId;
		this.modelo = modelo;
	}

	public ModeloBus(String modeloBusId, String modelo, String caracteristicas, Set buses) {
		this.modeloBusId = modeloBusId;
		this.modelo = modelo;
		this.caracteristicas = caracteristicas;
		this.buses = buses;
	}

	public String getModeloBusId() {
		return this.modeloBusId;
	}

	public void setModeloBusId(String modeloBusId) {
		this.modeloBusId = modeloBusId;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(String caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	public Set getBuses() {
		return this.buses;
	}

	public void setBuses(Set buses) {
		this.buses = buses;
	}

}
