package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String periodoId;
	private String periodo;
	private Date fechaInicio;
	private Date fechaFin;
	private String anotaciones;
	private Set cronogramas = new HashSet(0);

	public Periodo() {
	}

	public Periodo(String periodoId, String periodo, Date fechaInicio, Date fechaFin) {
		this.periodoId = periodoId;
		this.periodo = periodo;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Periodo(String periodoId, String periodo, Date fechaInicio, Date fechaFin, String anotaciones,
			Set cronogramas) {
		this.periodoId = periodoId;
		this.periodo = periodo;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.anotaciones = anotaciones;
		this.cronogramas = cronogramas;
	}

	public String getPeriodoId() {
		return this.periodoId;
	}

	public void setPeriodoId(String periodoId) {
		this.periodoId = periodoId;
	}

	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getAnotaciones() {
		return this.anotaciones;
	}

	public void setAnotaciones(String anotaciones) {
		this.anotaciones = anotaciones;
	}

	public Set getCronogramas() {
		return this.cronogramas;
	}

	public void setCronogramas(Set cronogramas) {
		this.cronogramas = cronogramas;
	}

}
