package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

/**
 * PermisoRol generated by hbm2java
 */
public class PermisoRol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String permisoRolId;
	private Permiso permiso;
	private Rol rol;

	public PermisoRol() {
	}

	public PermisoRol(String permisoRolId, Permiso permiso, Rol rol) {
		this.permisoRolId = permisoRolId;
		this.permiso = permiso;
		this.rol = rol;
	}

	public String getPermisoRolId() {
		return this.permisoRolId;
	}

	public void setPermisoRolId(String permisoRolId) {
		this.permisoRolId = permisoRolId;
	}

	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
