package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

/**
 * PropietarioBus generated by hbm2java
 */
public class PropietarioBus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String propietarioBusId;
	private Bus bus;
	private Socio socio;

	public PropietarioBus() {
	}

	public PropietarioBus(String propietarioBusId, Bus bus, Socio socio) {
		this.propietarioBusId = propietarioBusId;
		this.bus = bus;
		this.socio = socio;
	}

	public String getPropietarioBusId() {
		return this.propietarioBusId;
	}

	public void setPropietarioBusId(String propietarioBusId) {
		this.propietarioBusId = propietarioBusId;
	}

	public Bus getBus() {
		return this.bus;
	}

	public void setBus(Bus bus) {
		this.bus = bus;
	}

	public Socio getSocio() {
		return this.socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

}
