package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

/**
 * PuntoRuta generated by hbm2java
 */
public class PuntoRuta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String puntoRutaId;
	private Punto punto;
	private Ruta ruta;

	public PuntoRuta() {
	}

	public PuntoRuta(String puntoRutaId, Punto punto, Ruta ruta) {
		this.puntoRutaId = puntoRutaId;
		this.punto = punto;
		this.ruta = ruta;
	}

	public String getPuntoRutaId() {
		return this.puntoRutaId;
	}

	public void setPuntoRutaId(String puntoRutaId) {
		this.puntoRutaId = puntoRutaId;
	}

	public Punto getPunto() {
		return this.punto;
	}

	public void setPunto(Punto punto) {
		this.punto = punto;
	}

	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

}
