package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Punto generated by hbm2java
 */
public class Punto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String puntoId;
	private Locacion locacion;
	private String punto;
	private Set puntoRutas = new HashSet(0);

	public Punto() {
	}

	public Punto(String puntoId, Locacion locacion, String punto) {
		this.puntoId = puntoId;
		this.locacion = locacion;
		this.punto = punto;
	}

	public Punto(String puntoId, Locacion locacion, String punto, Set puntoRutas) {
		this.puntoId = puntoId;
		this.locacion = locacion;
		this.punto = punto;
		this.puntoRutas = puntoRutas;
	}

	public String getPuntoId() {
		return this.puntoId;
	}

	public void setPuntoId(String puntoId) {
		this.puntoId = puntoId;
	}

	public Locacion getLocacion() {
		return this.locacion;
	}

	public void setLocacion(Locacion locacion) {
		this.locacion = locacion;
	}

	public String getPunto() {
		return this.punto;
	}

	public void setPunto(String punto) {
		this.punto = punto;
	}

	public Set getPuntoRutas() {
		return this.puntoRutas;
	}

	public void setPuntoRutas(Set puntoRutas) {
		this.puntoRutas = puntoRutas;
	}

}
