package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * PuntoControl generated by hbm2java
 */
public class PuntoControl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String puntoControlId;
	private RecorridoTarjeta recorridoTarjeta;
	private Date horaEstablecida;
	private Date horaLlegada;
	private Integer diferencia;

	public PuntoControl() {
	}

	public PuntoControl(String puntoControlId, RecorridoTarjeta recorridoTarjeta, Date horaEstablecida) {
		this.puntoControlId = puntoControlId;
		this.recorridoTarjeta = recorridoTarjeta;
		this.horaEstablecida = horaEstablecida;
	}

	public PuntoControl(String puntoControlId, RecorridoTarjeta recorridoTarjeta, Date horaEstablecida,
			Date horaLlegada, Integer diferencia) {
		this.puntoControlId = puntoControlId;
		this.recorridoTarjeta = recorridoTarjeta;
		this.horaEstablecida = horaEstablecida;
		this.horaLlegada = horaLlegada;
		this.diferencia = diferencia;
	}

	public String getPuntoControlId() {
		return this.puntoControlId;
	}

	public void setPuntoControlId(String puntoControlId) {
		this.puntoControlId = puntoControlId;
	}

	public RecorridoTarjeta getRecorridoTarjeta() {
		return this.recorridoTarjeta;
	}

	public void setRecorridoTarjeta(RecorridoTarjeta recorridoTarjeta) {
		this.recorridoTarjeta = recorridoTarjeta;
	}

	public Date getHoraEstablecida() {
		return this.horaEstablecida;
	}

	public void setHoraEstablecida(Date horaEstablecida) {
		this.horaEstablecida = horaEstablecida;
	}

	public Date getHoraLlegada() {
		return this.horaLlegada;
	}

	public void setHoraLlegada(Date horaLlegada) {
		this.horaLlegada = horaLlegada;
	}

	public Integer getDiferencia() {
		return this.diferencia;
	}

	public void setDiferencia(Integer diferencia) {
		this.diferencia = diferencia;
	}

}
