package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * RecorridoTarjeta generated by hbm2java
 */
public class RecorridoTarjeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String recorridoTarjetaId;
	private SalidaBus salidaBus;
	private Tarjeta tarjeta;
	private int numeroRecorrido;
	private BigDecimal minutosRetraso;
	private String estadoRecorrido;
	private Set puntoControls = new HashSet(0);

	public RecorridoTarjeta() {
	}

	public RecorridoTarjeta(String recorridoTarjetaId, SalidaBus salidaBus, Tarjeta tarjeta, int numeroRecorrido,
			BigDecimal minutosRetraso) {
		this.recorridoTarjetaId = recorridoTarjetaId;
		this.salidaBus = salidaBus;
		this.tarjeta = tarjeta;
		this.numeroRecorrido = numeroRecorrido;
		this.minutosRetraso = minutosRetraso;
	}

	public RecorridoTarjeta(String recorridoTarjetaId, SalidaBus salidaBus, Tarjeta tarjeta, int numeroRecorrido,
			BigDecimal minutosRetraso, String estadoRecorrido, Set puntoControls) {
		this.recorridoTarjetaId = recorridoTarjetaId;
		this.salidaBus = salidaBus;
		this.tarjeta = tarjeta;
		this.numeroRecorrido = numeroRecorrido;
		this.minutosRetraso = minutosRetraso;
		this.estadoRecorrido = estadoRecorrido;
		this.puntoControls = puntoControls;
	}

	public String getRecorridoTarjetaId() {
		return this.recorridoTarjetaId;
	}

	public void setRecorridoTarjetaId(String recorridoTarjetaId) {
		this.recorridoTarjetaId = recorridoTarjetaId;
	}

	public SalidaBus getSalidaBus() {
		return this.salidaBus;
	}

	public void setSalidaBus(SalidaBus salidaBus) {
		this.salidaBus = salidaBus;
	}

	public Tarjeta getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Tarjeta tarjeta) {
		this.tarjeta = tarjeta;
	}

	public int getNumeroRecorrido() {
		return this.numeroRecorrido;
	}

	public void setNumeroRecorrido(int numeroRecorrido) {
		this.numeroRecorrido = numeroRecorrido;
	}

	public BigDecimal getMinutosRetraso() {
		return this.minutosRetraso;
	}

	public void setMinutosRetraso(BigDecimal minutosRetraso) {
		this.minutosRetraso = minutosRetraso;
	}

	public String getEstadoRecorrido() {
		return this.estadoRecorrido;
	}

	public void setEstadoRecorrido(String estadoRecorrido) {
		this.estadoRecorrido = estadoRecorrido;
	}

	public Set getPuntoControls() {
		return this.puntoControls;
	}

	public void setPuntoControls(Set puntoControls) {
		this.puntoControls = puntoControls;
	}

}
