package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String rolId;
	private String rol;
	private String descripcion;
	private Set usuarios = new HashSet(0);
	private Set permisoRols = new HashSet(0);

	public Rol() {
	}

	public Rol(String rolId, String rol) {
		this.rolId = rolId;
		this.rol = rol;
	}

	public Rol(String rolId, String rol, String descripcion, Set usuarios, Set permisoRols) {
		this.rolId = rolId;
		this.rol = rol;
		this.descripcion = descripcion;
		this.usuarios = usuarios;
		this.permisoRols = permisoRols;
	}

	public String getRolId() {
		return this.rolId;
	}

	public void setRolId(String rolId) {
		this.rolId = rolId;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getPermisoRols() {
		return this.permisoRols;
	}

	public void setPermisoRols(Set permisoRols) {
		this.permisoRols = permisoRols;
	}

}
