package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Ruta generated by hbm2java
 */
public class Ruta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String rutaId;
	private String identificador;
	private Set puntoRutas = new HashSet(0);
	private Set detalleCronogramas = new HashSet(0);

	public Ruta() {
	}

	public Ruta(String rutaId, String identificador) {
		this.rutaId = rutaId;
		this.identificador = identificador;
	}

	public Ruta(String rutaId, String identificador, Set puntoRutas, Set detalleCronogramas) {
		this.rutaId = rutaId;
		this.identificador = identificador;
		this.puntoRutas = puntoRutas;
		this.detalleCronogramas = detalleCronogramas;
	}

	public String getRutaId() {
		return this.rutaId;
	}

	public void setRutaId(String rutaId) {
		this.rutaId = rutaId;
	}

	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public Set getPuntoRutas() {
		return this.puntoRutas;
	}

	public void setPuntoRutas(Set puntoRutas) {
		this.puntoRutas = puntoRutas;
	}

	public Set getDetalleCronogramas() {
		return this.detalleCronogramas;
	}

	public void setDetalleCronogramas(Set detalleCronogramas) {
		this.detalleCronogramas = detalleCronogramas;
	}

}
