package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SalidaBus generated by hbm2java
 */
public class SalidaBus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String salidaBusId;
	private DetalleCronograma detalleCronograma;
	private DetalleGrupo detalleGrupo;
	private Date fechaSalida;
	private Date horaSalida;
	private Set recorridoTarjetas = new HashSet(0);
	private Set incidencias = new HashSet(0);

	public SalidaBus() {
	}

	public SalidaBus(String salidaBusId, DetalleCronograma detalleCronograma, DetalleGrupo detalleGrupo,
			Date fechaSalida, Date horaSalida) {
		this.salidaBusId = salidaBusId;
		this.detalleCronograma = detalleCronograma;
		this.detalleGrupo = detalleGrupo;
		this.fechaSalida = fechaSalida;
		this.horaSalida = horaSalida;
	}

	public SalidaBus(String salidaBusId, DetalleCronograma detalleCronograma, DetalleGrupo detalleGrupo,
			Date fechaSalida, Date horaSalida, Set recorridoTarjetas, Set incidencias) {
		this.salidaBusId = salidaBusId;
		this.detalleCronograma = detalleCronograma;
		this.detalleGrupo = detalleGrupo;
		this.fechaSalida = fechaSalida;
		this.horaSalida = horaSalida;
		this.recorridoTarjetas = recorridoTarjetas;
		this.incidencias = incidencias;
	}

	public String getSalidaBusId() {
		return this.salidaBusId;
	}

	public void setSalidaBusId(String salidaBusId) {
		this.salidaBusId = salidaBusId;
	}

	public DetalleCronograma getDetalleCronograma() {
		return this.detalleCronograma;
	}

	public void setDetalleCronograma(DetalleCronograma detalleCronograma) {
		this.detalleCronograma = detalleCronograma;
	}

	public DetalleGrupo getDetalleGrupo() {
		return this.detalleGrupo;
	}

	public void setDetalleGrupo(DetalleGrupo detalleGrupo) {
		this.detalleGrupo = detalleGrupo;
	}

	public Date getFechaSalida() {
		return this.fechaSalida;
	}

	public void setFechaSalida(Date fechaSalida) {
		this.fechaSalida = fechaSalida;
	}

	public Date getHoraSalida() {
		return this.horaSalida;
	}

	public void setHoraSalida(Date horaSalida) {
		this.horaSalida = horaSalida;
	}

	public Set getRecorridoTarjetas() {
		return this.recorridoTarjetas;
	}

	public void setRecorridoTarjetas(Set recorridoTarjetas) {
		this.recorridoTarjetas = recorridoTarjetas;
	}

	public Set getIncidencias() {
		return this.incidencias;
	}

	public void setIncidencias(Set incidencias) {
		this.incidencias = incidencias;
	}

}
