package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */
public class Socio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String socioId;
	private Locacion locacion;
	private TipoSocio tipoSocio;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String dni;
	private String razonSocial;
	private String ruc;
	private String telefono;
	private String movil;
	private String direccion;
	private String email;
	private Set propietarioBuses = new HashSet(0);
	private Set usuarios = new HashSet(0);

	public Socio() {
	}

	public Socio(String socioId, Locacion locacion, TipoSocio tipoSocio) {
		this.socioId = socioId;
		this.locacion = locacion;
		this.tipoSocio = tipoSocio;
	}

	public Socio(String socioId, Locacion locacion, TipoSocio tipoSocio, String nombres, String apellidoPaterno,
			String apellidoMaterno, String dni, String razonSocial, String ruc, String telefono, String movil,
			String direccion, String email, Set propietarioBuses, Set usuarios) {
		this.socioId = socioId;
		this.locacion = locacion;
		this.tipoSocio = tipoSocio;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.dni = dni;
		this.razonSocial = razonSocial;
		this.ruc = ruc;
		this.telefono = telefono;
		this.movil = movil;
		this.direccion = direccion;
		this.email = email;
		this.propietarioBuses = propietarioBuses;
		this.usuarios = usuarios;
	}

	public String getSocioId() {
		return this.socioId;
	}

	public void setSocioId(String socioId) {
		this.socioId = socioId;
	}

	public Locacion getLocacion() {
		return this.locacion;
	}

	public void setLocacion(Locacion locacion) {
		this.locacion = locacion;
	}

	public TipoSocio getTipoSocio() {
		return this.tipoSocio;
	}

	public void setTipoSocio(TipoSocio tipoSocio) {
		this.tipoSocio = tipoSocio;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getMovil() {
		return this.movil;
	}

	public void setMovil(String movil) {
		this.movil = movil;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getPropietarioBuses() {
		return this.propietarioBuses;
	}

	public void setPropietarioBuses(Set propietarioBuses) {
		this.propietarioBuses = propietarioBuses;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
