package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String tarjetaId;
	private Bus bus;
	private String numero;
	private Date fechaEmision;
	private Set recorridoTarjetas = new HashSet(0);

	public Tarjeta() {
	}

	public Tarjeta(String tarjetaId, Bus bus, String numero, Date fechaEmision) {
		this.tarjetaId = tarjetaId;
		this.bus = bus;
		this.numero = numero;
		this.fechaEmision = fechaEmision;
	}

	public Tarjeta(String tarjetaId, Bus bus, String numero, Date fechaEmision, Set recorridoTarjetas) {
		this.tarjetaId = tarjetaId;
		this.bus = bus;
		this.numero = numero;
		this.fechaEmision = fechaEmision;
		this.recorridoTarjetas = recorridoTarjetas;
	}

	public String getTarjetaId() {
		return this.tarjetaId;
	}

	public void setTarjetaId(String tarjetaId) {
		this.tarjetaId = tarjetaId;
	}

	public Bus getBus() {
		return this.bus;
	}

	public void setBus(Bus bus) {
		this.bus = bus;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public Set getRecorridoTarjetas() {
		return this.recorridoTarjetas;
	}

	public void setRecorridoTarjetas(Set recorridoTarjetas) {
		this.recorridoTarjetas = recorridoTarjetas;
	}

}
