package com.tesis.ptspring.modelEntities;
// Generated 12/08/2018 11:51:29 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * TipoSocio generated by hbm2java
 */
public class TipoSocio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String tipoSocioId;
	private String tipoSocio;
	private String codigoIdentificacion;
	private String descripcion;
	private Set socios = new HashSet(0);

	public TipoSocio() {
	}

	public TipoSocio(String tipoSocioId, String tipoSocio, String codigoIdentificacion) {
		this.tipoSocioId = tipoSocioId;
		this.tipoSocio = tipoSocio;
		this.codigoIdentificacion = codigoIdentificacion;
	}

	public TipoSocio(String tipoSocioId, String tipoSocio, String codigoIdentificacion, String descripcion,
			Set socios) {
		this.tipoSocioId = tipoSocioId;
		this.tipoSocio = tipoSocio;
		this.codigoIdentificacion = codigoIdentificacion;
		this.descripcion = descripcion;
		this.socios = socios;
	}

	public String getTipoSocioId() {
		return this.tipoSocioId;
	}

	public void setTipoSocioId(String tipoSocioId) {
		this.tipoSocioId = tipoSocioId;
	}

	public String getTipoSocio() {
		return this.tipoSocio;
	}

	public void setTipoSocio(String tipoSocio) {
		this.tipoSocio = tipoSocio;
	}

	public String getCodigoIdentificacion() {
		return this.codigoIdentificacion;
	}

	public void setCodigoIdentificacion(String codigoIdentificacion) {
		this.codigoIdentificacion = codigoIdentificacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getSocios() {
		return this.socios;
	}

	public void setSocios(Set socios) {
		this.socios = socios;
	}

}
